// Code generated by ent, DO NOT EDIT.

package calendar

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/AvengeMedia/dankcalendar/core/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Calendar {
	return predicate.Calendar(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Calendar {
	return predicate.Calendar(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Calendar {
	return predicate.Calendar(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Calendar {
	return predicate.Calendar(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Calendar {
	return predicate.Calendar(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Calendar {
	return predicate.Calendar(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Calendar {
	return predicate.Calendar(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Calendar {
	return predicate.Calendar(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Calendar {
	return predicate.Calendar(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Calendar {
	return predicate.Calendar(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Calendar {
	return predicate.Calendar(sql.FieldContainsFold(FieldID, id))
}

// RemoteID applies equality check predicate on the "remote_id" field. It's identical to RemoteIDEQ.
func RemoteID(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldEQ(FieldRemoteID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldEQ(FieldName, v))
}

// NameOverride applies equality check predicate on the "name_override" field. It's identical to NameOverrideEQ.
func NameOverride(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldEQ(FieldNameOverride, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldEQ(FieldDescription, v))
}

// Color applies equality check predicate on the "color" field. It's identical to ColorEQ.
func Color(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldEQ(FieldColor, v))
}

// ColorOverride applies equality check predicate on the "color_override" field. It's identical to ColorOverrideEQ.
func ColorOverride(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldEQ(FieldColorOverride, v))
}

// TimeZone applies equality check predicate on the "time_zone" field. It's identical to TimeZoneEQ.
func TimeZone(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldEQ(FieldTimeZone, v))
}

// ReadOnly applies equality check predicate on the "read_only" field. It's identical to ReadOnlyEQ.
func ReadOnly(v bool) predicate.Calendar {
	return predicate.Calendar(sql.FieldEQ(FieldReadOnly, v))
}

// Hidden applies equality check predicate on the "hidden" field. It's identical to HiddenEQ.
func Hidden(v bool) predicate.Calendar {
	return predicate.Calendar(sql.FieldEQ(FieldHidden, v))
}

// SyncDisabled applies equality check predicate on the "sync_disabled" field. It's identical to SyncDisabledEQ.
func SyncDisabled(v bool) predicate.Calendar {
	return predicate.Calendar(sql.FieldEQ(FieldSyncDisabled, v))
}

// SyncToken applies equality check predicate on the "sync_token" field. It's identical to SyncTokenEQ.
func SyncToken(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldEQ(FieldSyncToken, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Calendar {
	return predicate.Calendar(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Calendar {
	return predicate.Calendar(sql.FieldEQ(FieldUpdatedAt, v))
}

// RemoteIDEQ applies the EQ predicate on the "remote_id" field.
func RemoteIDEQ(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldEQ(FieldRemoteID, v))
}

// RemoteIDNEQ applies the NEQ predicate on the "remote_id" field.
func RemoteIDNEQ(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldNEQ(FieldRemoteID, v))
}

// RemoteIDIn applies the In predicate on the "remote_id" field.
func RemoteIDIn(vs ...string) predicate.Calendar {
	return predicate.Calendar(sql.FieldIn(FieldRemoteID, vs...))
}

// RemoteIDNotIn applies the NotIn predicate on the "remote_id" field.
func RemoteIDNotIn(vs ...string) predicate.Calendar {
	return predicate.Calendar(sql.FieldNotIn(FieldRemoteID, vs...))
}

// RemoteIDGT applies the GT predicate on the "remote_id" field.
func RemoteIDGT(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldGT(FieldRemoteID, v))
}

// RemoteIDGTE applies the GTE predicate on the "remote_id" field.
func RemoteIDGTE(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldGTE(FieldRemoteID, v))
}

// RemoteIDLT applies the LT predicate on the "remote_id" field.
func RemoteIDLT(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldLT(FieldRemoteID, v))
}

// RemoteIDLTE applies the LTE predicate on the "remote_id" field.
func RemoteIDLTE(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldLTE(FieldRemoteID, v))
}

// RemoteIDContains applies the Contains predicate on the "remote_id" field.
func RemoteIDContains(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldContains(FieldRemoteID, v))
}

// RemoteIDHasPrefix applies the HasPrefix predicate on the "remote_id" field.
func RemoteIDHasPrefix(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldHasPrefix(FieldRemoteID, v))
}

// RemoteIDHasSuffix applies the HasSuffix predicate on the "remote_id" field.
func RemoteIDHasSuffix(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldHasSuffix(FieldRemoteID, v))
}

// RemoteIDEqualFold applies the EqualFold predicate on the "remote_id" field.
func RemoteIDEqualFold(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldEqualFold(FieldRemoteID, v))
}

// RemoteIDContainsFold applies the ContainsFold predicate on the "remote_id" field.
func RemoteIDContainsFold(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldContainsFold(FieldRemoteID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Calendar {
	return predicate.Calendar(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Calendar {
	return predicate.Calendar(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldContainsFold(FieldName, v))
}

// NameOverrideEQ applies the EQ predicate on the "name_override" field.
func NameOverrideEQ(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldEQ(FieldNameOverride, v))
}

// NameOverrideNEQ applies the NEQ predicate on the "name_override" field.
func NameOverrideNEQ(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldNEQ(FieldNameOverride, v))
}

// NameOverrideIn applies the In predicate on the "name_override" field.
func NameOverrideIn(vs ...string) predicate.Calendar {
	return predicate.Calendar(sql.FieldIn(FieldNameOverride, vs...))
}

// NameOverrideNotIn applies the NotIn predicate on the "name_override" field.
func NameOverrideNotIn(vs ...string) predicate.Calendar {
	return predicate.Calendar(sql.FieldNotIn(FieldNameOverride, vs...))
}

// NameOverrideGT applies the GT predicate on the "name_override" field.
func NameOverrideGT(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldGT(FieldNameOverride, v))
}

// NameOverrideGTE applies the GTE predicate on the "name_override" field.
func NameOverrideGTE(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldGTE(FieldNameOverride, v))
}

// NameOverrideLT applies the LT predicate on the "name_override" field.
func NameOverrideLT(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldLT(FieldNameOverride, v))
}

// NameOverrideLTE applies the LTE predicate on the "name_override" field.
func NameOverrideLTE(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldLTE(FieldNameOverride, v))
}

// NameOverrideContains applies the Contains predicate on the "name_override" field.
func NameOverrideContains(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldContains(FieldNameOverride, v))
}

// NameOverrideHasPrefix applies the HasPrefix predicate on the "name_override" field.
func NameOverrideHasPrefix(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldHasPrefix(FieldNameOverride, v))
}

// NameOverrideHasSuffix applies the HasSuffix predicate on the "name_override" field.
func NameOverrideHasSuffix(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldHasSuffix(FieldNameOverride, v))
}

// NameOverrideIsNil applies the IsNil predicate on the "name_override" field.
func NameOverrideIsNil() predicate.Calendar {
	return predicate.Calendar(sql.FieldIsNull(FieldNameOverride))
}

// NameOverrideNotNil applies the NotNil predicate on the "name_override" field.
func NameOverrideNotNil() predicate.Calendar {
	return predicate.Calendar(sql.FieldNotNull(FieldNameOverride))
}

// NameOverrideEqualFold applies the EqualFold predicate on the "name_override" field.
func NameOverrideEqualFold(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldEqualFold(FieldNameOverride, v))
}

// NameOverrideContainsFold applies the ContainsFold predicate on the "name_override" field.
func NameOverrideContainsFold(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldContainsFold(FieldNameOverride, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Calendar {
	return predicate.Calendar(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Calendar {
	return predicate.Calendar(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Calendar {
	return predicate.Calendar(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Calendar {
	return predicate.Calendar(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldContainsFold(FieldDescription, v))
}

// ColorEQ applies the EQ predicate on the "color" field.
func ColorEQ(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldEQ(FieldColor, v))
}

// ColorNEQ applies the NEQ predicate on the "color" field.
func ColorNEQ(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldNEQ(FieldColor, v))
}

// ColorIn applies the In predicate on the "color" field.
func ColorIn(vs ...string) predicate.Calendar {
	return predicate.Calendar(sql.FieldIn(FieldColor, vs...))
}

// ColorNotIn applies the NotIn predicate on the "color" field.
func ColorNotIn(vs ...string) predicate.Calendar {
	return predicate.Calendar(sql.FieldNotIn(FieldColor, vs...))
}

// ColorGT applies the GT predicate on the "color" field.
func ColorGT(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldGT(FieldColor, v))
}

// ColorGTE applies the GTE predicate on the "color" field.
func ColorGTE(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldGTE(FieldColor, v))
}

// ColorLT applies the LT predicate on the "color" field.
func ColorLT(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldLT(FieldColor, v))
}

// ColorLTE applies the LTE predicate on the "color" field.
func ColorLTE(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldLTE(FieldColor, v))
}

// ColorContains applies the Contains predicate on the "color" field.
func ColorContains(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldContains(FieldColor, v))
}

// ColorHasPrefix applies the HasPrefix predicate on the "color" field.
func ColorHasPrefix(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldHasPrefix(FieldColor, v))
}

// ColorHasSuffix applies the HasSuffix predicate on the "color" field.
func ColorHasSuffix(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldHasSuffix(FieldColor, v))
}

// ColorIsNil applies the IsNil predicate on the "color" field.
func ColorIsNil() predicate.Calendar {
	return predicate.Calendar(sql.FieldIsNull(FieldColor))
}

// ColorNotNil applies the NotNil predicate on the "color" field.
func ColorNotNil() predicate.Calendar {
	return predicate.Calendar(sql.FieldNotNull(FieldColor))
}

// ColorEqualFold applies the EqualFold predicate on the "color" field.
func ColorEqualFold(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldEqualFold(FieldColor, v))
}

// ColorContainsFold applies the ContainsFold predicate on the "color" field.
func ColorContainsFold(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldContainsFold(FieldColor, v))
}

// ColorOverrideEQ applies the EQ predicate on the "color_override" field.
func ColorOverrideEQ(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldEQ(FieldColorOverride, v))
}

// ColorOverrideNEQ applies the NEQ predicate on the "color_override" field.
func ColorOverrideNEQ(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldNEQ(FieldColorOverride, v))
}

// ColorOverrideIn applies the In predicate on the "color_override" field.
func ColorOverrideIn(vs ...string) predicate.Calendar {
	return predicate.Calendar(sql.FieldIn(FieldColorOverride, vs...))
}

// ColorOverrideNotIn applies the NotIn predicate on the "color_override" field.
func ColorOverrideNotIn(vs ...string) predicate.Calendar {
	return predicate.Calendar(sql.FieldNotIn(FieldColorOverride, vs...))
}

// ColorOverrideGT applies the GT predicate on the "color_override" field.
func ColorOverrideGT(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldGT(FieldColorOverride, v))
}

// ColorOverrideGTE applies the GTE predicate on the "color_override" field.
func ColorOverrideGTE(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldGTE(FieldColorOverride, v))
}

// ColorOverrideLT applies the LT predicate on the "color_override" field.
func ColorOverrideLT(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldLT(FieldColorOverride, v))
}

// ColorOverrideLTE applies the LTE predicate on the "color_override" field.
func ColorOverrideLTE(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldLTE(FieldColorOverride, v))
}

// ColorOverrideContains applies the Contains predicate on the "color_override" field.
func ColorOverrideContains(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldContains(FieldColorOverride, v))
}

// ColorOverrideHasPrefix applies the HasPrefix predicate on the "color_override" field.
func ColorOverrideHasPrefix(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldHasPrefix(FieldColorOverride, v))
}

// ColorOverrideHasSuffix applies the HasSuffix predicate on the "color_override" field.
func ColorOverrideHasSuffix(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldHasSuffix(FieldColorOverride, v))
}

// ColorOverrideIsNil applies the IsNil predicate on the "color_override" field.
func ColorOverrideIsNil() predicate.Calendar {
	return predicate.Calendar(sql.FieldIsNull(FieldColorOverride))
}

// ColorOverrideNotNil applies the NotNil predicate on the "color_override" field.
func ColorOverrideNotNil() predicate.Calendar {
	return predicate.Calendar(sql.FieldNotNull(FieldColorOverride))
}

// ColorOverrideEqualFold applies the EqualFold predicate on the "color_override" field.
func ColorOverrideEqualFold(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldEqualFold(FieldColorOverride, v))
}

// ColorOverrideContainsFold applies the ContainsFold predicate on the "color_override" field.
func ColorOverrideContainsFold(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldContainsFold(FieldColorOverride, v))
}

// TimeZoneEQ applies the EQ predicate on the "time_zone" field.
func TimeZoneEQ(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldEQ(FieldTimeZone, v))
}

// TimeZoneNEQ applies the NEQ predicate on the "time_zone" field.
func TimeZoneNEQ(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldNEQ(FieldTimeZone, v))
}

// TimeZoneIn applies the In predicate on the "time_zone" field.
func TimeZoneIn(vs ...string) predicate.Calendar {
	return predicate.Calendar(sql.FieldIn(FieldTimeZone, vs...))
}

// TimeZoneNotIn applies the NotIn predicate on the "time_zone" field.
func TimeZoneNotIn(vs ...string) predicate.Calendar {
	return predicate.Calendar(sql.FieldNotIn(FieldTimeZone, vs...))
}

// TimeZoneGT applies the GT predicate on the "time_zone" field.
func TimeZoneGT(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldGT(FieldTimeZone, v))
}

// TimeZoneGTE applies the GTE predicate on the "time_zone" field.
func TimeZoneGTE(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldGTE(FieldTimeZone, v))
}

// TimeZoneLT applies the LT predicate on the "time_zone" field.
func TimeZoneLT(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldLT(FieldTimeZone, v))
}

// TimeZoneLTE applies the LTE predicate on the "time_zone" field.
func TimeZoneLTE(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldLTE(FieldTimeZone, v))
}

// TimeZoneContains applies the Contains predicate on the "time_zone" field.
func TimeZoneContains(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldContains(FieldTimeZone, v))
}

// TimeZoneHasPrefix applies the HasPrefix predicate on the "time_zone" field.
func TimeZoneHasPrefix(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldHasPrefix(FieldTimeZone, v))
}

// TimeZoneHasSuffix applies the HasSuffix predicate on the "time_zone" field.
func TimeZoneHasSuffix(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldHasSuffix(FieldTimeZone, v))
}

// TimeZoneIsNil applies the IsNil predicate on the "time_zone" field.
func TimeZoneIsNil() predicate.Calendar {
	return predicate.Calendar(sql.FieldIsNull(FieldTimeZone))
}

// TimeZoneNotNil applies the NotNil predicate on the "time_zone" field.
func TimeZoneNotNil() predicate.Calendar {
	return predicate.Calendar(sql.FieldNotNull(FieldTimeZone))
}

// TimeZoneEqualFold applies the EqualFold predicate on the "time_zone" field.
func TimeZoneEqualFold(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldEqualFold(FieldTimeZone, v))
}

// TimeZoneContainsFold applies the ContainsFold predicate on the "time_zone" field.
func TimeZoneContainsFold(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldContainsFold(FieldTimeZone, v))
}

// ReadOnlyEQ applies the EQ predicate on the "read_only" field.
func ReadOnlyEQ(v bool) predicate.Calendar {
	return predicate.Calendar(sql.FieldEQ(FieldReadOnly, v))
}

// ReadOnlyNEQ applies the NEQ predicate on the "read_only" field.
func ReadOnlyNEQ(v bool) predicate.Calendar {
	return predicate.Calendar(sql.FieldNEQ(FieldReadOnly, v))
}

// HiddenEQ applies the EQ predicate on the "hidden" field.
func HiddenEQ(v bool) predicate.Calendar {
	return predicate.Calendar(sql.FieldEQ(FieldHidden, v))
}

// HiddenNEQ applies the NEQ predicate on the "hidden" field.
func HiddenNEQ(v bool) predicate.Calendar {
	return predicate.Calendar(sql.FieldNEQ(FieldHidden, v))
}

// SyncDisabledEQ applies the EQ predicate on the "sync_disabled" field.
func SyncDisabledEQ(v bool) predicate.Calendar {
	return predicate.Calendar(sql.FieldEQ(FieldSyncDisabled, v))
}

// SyncDisabledNEQ applies the NEQ predicate on the "sync_disabled" field.
func SyncDisabledNEQ(v bool) predicate.Calendar {
	return predicate.Calendar(sql.FieldNEQ(FieldSyncDisabled, v))
}

// ReminderOverridesIsNil applies the IsNil predicate on the "reminder_overrides" field.
func ReminderOverridesIsNil() predicate.Calendar {
	return predicate.Calendar(sql.FieldIsNull(FieldReminderOverrides))
}

// ReminderOverridesNotNil applies the NotNil predicate on the "reminder_overrides" field.
func ReminderOverridesNotNil() predicate.Calendar {
	return predicate.Calendar(sql.FieldNotNull(FieldReminderOverrides))
}

// SyncTokenEQ applies the EQ predicate on the "sync_token" field.
func SyncTokenEQ(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldEQ(FieldSyncToken, v))
}

// SyncTokenNEQ applies the NEQ predicate on the "sync_token" field.
func SyncTokenNEQ(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldNEQ(FieldSyncToken, v))
}

// SyncTokenIn applies the In predicate on the "sync_token" field.
func SyncTokenIn(vs ...string) predicate.Calendar {
	return predicate.Calendar(sql.FieldIn(FieldSyncToken, vs...))
}

// SyncTokenNotIn applies the NotIn predicate on the "sync_token" field.
func SyncTokenNotIn(vs ...string) predicate.Calendar {
	return predicate.Calendar(sql.FieldNotIn(FieldSyncToken, vs...))
}

// SyncTokenGT applies the GT predicate on the "sync_token" field.
func SyncTokenGT(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldGT(FieldSyncToken, v))
}

// SyncTokenGTE applies the GTE predicate on the "sync_token" field.
func SyncTokenGTE(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldGTE(FieldSyncToken, v))
}

// SyncTokenLT applies the LT predicate on the "sync_token" field.
func SyncTokenLT(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldLT(FieldSyncToken, v))
}

// SyncTokenLTE applies the LTE predicate on the "sync_token" field.
func SyncTokenLTE(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldLTE(FieldSyncToken, v))
}

// SyncTokenContains applies the Contains predicate on the "sync_token" field.
func SyncTokenContains(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldContains(FieldSyncToken, v))
}

// SyncTokenHasPrefix applies the HasPrefix predicate on the "sync_token" field.
func SyncTokenHasPrefix(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldHasPrefix(FieldSyncToken, v))
}

// SyncTokenHasSuffix applies the HasSuffix predicate on the "sync_token" field.
func SyncTokenHasSuffix(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldHasSuffix(FieldSyncToken, v))
}

// SyncTokenIsNil applies the IsNil predicate on the "sync_token" field.
func SyncTokenIsNil() predicate.Calendar {
	return predicate.Calendar(sql.FieldIsNull(FieldSyncToken))
}

// SyncTokenNotNil applies the NotNil predicate on the "sync_token" field.
func SyncTokenNotNil() predicate.Calendar {
	return predicate.Calendar(sql.FieldNotNull(FieldSyncToken))
}

// SyncTokenEqualFold applies the EqualFold predicate on the "sync_token" field.
func SyncTokenEqualFold(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldEqualFold(FieldSyncToken, v))
}

// SyncTokenContainsFold applies the ContainsFold predicate on the "sync_token" field.
func SyncTokenContainsFold(v string) predicate.Calendar {
	return predicate.Calendar(sql.FieldContainsFold(FieldSyncToken, v))
}

// SupportedComponentsIsNil applies the IsNil predicate on the "supported_components" field.
func SupportedComponentsIsNil() predicate.Calendar {
	return predicate.Calendar(sql.FieldIsNull(FieldSupportedComponents))
}

// SupportedComponentsNotNil applies the NotNil predicate on the "supported_components" field.
func SupportedComponentsNotNil() predicate.Calendar {
	return predicate.Calendar(sql.FieldNotNull(FieldSupportedComponents))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Calendar {
	return predicate.Calendar(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Calendar {
	return predicate.Calendar(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Calendar {
	return predicate.Calendar(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Calendar {
	return predicate.Calendar(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Calendar {
	return predicate.Calendar(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Calendar {
	return predicate.Calendar(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Calendar {
	return predicate.Calendar(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Calendar {
	return predicate.Calendar(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Calendar {
	return predicate.Calendar(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Calendar {
	return predicate.Calendar(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Calendar {
	return predicate.Calendar(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Calendar {
	return predicate.Calendar(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Calendar {
	return predicate.Calendar(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Calendar {
	return predicate.Calendar(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Calendar {
	return predicate.Calendar(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Calendar {
	return predicate.Calendar(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasAccount applies the HasEdge predicate on the "account" edge.
func HasAccount() predicate.Calendar {
	return predicate.Calendar(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AccountTable, AccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountWith applies the HasEdge predicate on the "account" edge with a given conditions (other predicates).
func HasAccountWith(preds ...predicate.Account) predicate.Calendar {
	return predicate.Calendar(func(s *sql.Selector) {
		step := newAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEvents applies the HasEdge predicate on the "events" edge.
func HasEvents() predicate.Calendar {
	return predicate.Calendar(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, EventsTable, EventsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEventsWith applies the HasEdge predicate on the "events" edge with a given conditions (other predicates).
func HasEventsWith(preds ...predicate.Event) predicate.Calendar {
	return predicate.Calendar(func(s *sql.Selector) {
		step := newEventsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTasks applies the HasEdge predicate on the "tasks" edge.
func HasTasks() predicate.Calendar {
	return predicate.Calendar(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TasksTable, TasksColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTasksWith applies the HasEdge predicate on the "tasks" edge with a given conditions (other predicates).
func HasTasksWith(preds ...predicate.Task) predicate.Calendar {
	return predicate.Calendar(func(s *sql.Selector) {
		step := newTasksStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Calendar) predicate.Calendar {
	return predicate.Calendar(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Calendar) predicate.Calendar {
	return predicate.Calendar(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Calendar) predicate.Calendar {
	return predicate.Calendar(sql.NotPredicates(p))
}
